<?php

namespace Bshared\BsharedBundle\Repository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLatest()
    {
        $req = $this->createQueryBuilder('u');

        $req->setMaxResults(20);

        return $req->getQuery()->getResult();

    }
}
